# Generated by Django 6.0.6 on 2026-06-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='srblh',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PlantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('marked', models.BooleanField(default=False)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_categories', to='crops.crop')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='crops.plant')),
            ],
        ),
    ]
