# Generated by Django 6.0.6 on 2026-06-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_plant_srblh_plantcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='bunch',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
