# Generated by Django 6.0.6 on 2026-07-02 08:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_plant_bunch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('bool', 'Yes/No'), ('int', 'Whole number'), ('float', 'Decimal number'), ('text', 'Text')], max_length=5)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_attributes', to='crops.crop')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantAttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='crops.plantattribute')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='crops.plant')),
            ],
        ),
        migrations.DeleteModel(
            name='PlantCategory',
        ),
        migrations.AddConstraint(
            model_name='plantattribute',
            constraint=models.UniqueConstraint(fields=('crop', 'name'), name='unique_attribute_per_crop'),
        ),
        migrations.AddConstraint(
            model_name='plantattributevalue',
            constraint=models.UniqueConstraint(fields=('attribute', 'plant'), name='one_value_per_plant_per_attribute'),
        ),
    ]
