# Generated by Django 6.0.6 on 2026-07-02 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0001_initial'),
        ('tasks', '0002_task_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_transaction', to='tasks.task'),
        ),
    ]
